name: markdown_quill
description: Convert between quill (delta) format and markdown
publish_to: "none"
version: 1.0.6
repository: https://github.com/FerryAr/markdown_quill

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.16.0
  flutter_quill:
    git:
      url: https://github.com/FerryAr/flutter-quill
  markdown: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  very_good_analysis: ^3.1.0
